### ISSUE TITLE
When you want to ask a question...

### ISSUE THREAD

**Issue by blackslate** [RachelQ1103/learnpython#1]
... you can create an Issue, and I will receive a notification about it. I can create a fork of any repository you are working on, make a change and send you a [pull request](https://help.github.com/articles/using-pull-requests/) so that you can see my changes and decide whether you want to include them in your repository or not.

玩得开心点。

**Comment by RachelQ1103** [comment]
I see. ^ ^ Thanks~

**Comment by blackslate** [comment]
It works!
